djangoboiler/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from app.views import ViewProjeto, ListProjetos, IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('projetos/', ListProjetos.as_view(), name='projetos'),
    path('projeto/<pk>', ViewProjeto.as_view(), name='verprojeto'),
    path('submit', views.submit, name='submit'),
]

app/models.py
from __future__ import unicode_literals

from base64 import b64encode

import pyimgur
from ckeditor.fields import RichTextField
from django.db import models


# Create your models here.


class Contato(models.Model):
    nome = models.CharField(max_length=100, blank=False)
    sobrenome = models.CharField(max_length=100)
    email = models.EmailField(blank=False)
    mensagem = models.TextField(blank=False)

    def __str__(self):  # __unicode__ on Python 2
        return str(self.nome).upper() + str(self.sobrenome).upper()


class Categoria(models.Model):
    tag = models.CharField(max_length=100)
    criado_em = models.DateTimeField(auto_now_add=True)
    editado_em = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u'%s' % (self.tag)


class Projeto(models.Model):
    titulo = models.CharField(max_length=100, blank=True, null=True)
    desc = models.TextField(max_length=200)
    texto = models.TextField(blank=True, null=True)
    categoria = models.ForeignKey(Categoria, blank=True, null=True, on_delete=models.CASCADE)
    criado_em = models.DateTimeField(auto_now_add=True)
    editado_em = models.DateTimeField(auto_now=True)
    visivel = models.BooleanField(default=True)

    def __str__(self):  # __unicode__ on Python 2
        return str(self.titulo)

    def __unicode__(self):
        return u'%s' % (self.titulo)


class Foto(models.Model):
    file = models.FileField(blank=True, null=True)
    foto = models.URLField(blank=True, null=True, default='https://placehold.it/300x300')
    model = models.ForeignKey(Projeto, blank=True, null=True, on_delete=models.CASCADE)
    principal = models.BooleanField(default=False)
    criado_em = models.DateTimeField(auto_now_add=True)
    editado_em = models.DateTimeField(auto_now=True)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        try:
            CLIENT_ID = "cdadf801dc167ab"
            bencode = b64encode(self.file.read())
            client = pyimgur.Imgur(CLIENT_ID)
            r = client._send_request('https://api.imgur.com/3/image', method='POST', params={'image': bencode})
            file = r['link']
            self.foto = file
        except (Exception,):
            pass
        super(Foto, self).save(force_insert=force_insert, force_update=force_update, using=using,
                               update_fields=update_fields)

app/views.py
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView

from app.models import *


class IndexView(ListView):
    template_name = 'index.html'
    model = Projeto
    context_object_name = 'projetos'

    def get_queryset(self):
        return Projeto.objects.filter(visivel=True).order_by('-criado_em')[:3]


class ListProjetos(ListView):
    template_name = 'projetos.html'
    model = Projeto
    context_object_name = 'projetos'

    def get_queryset(self):
        return Projeto.objects.filter(visivel=True)


class ViewProjeto(DetailView):
    model = Projeto
    template_name = 'ver_projeto.html'
    context_object_name = 'projeto'


def submit(request):
    data = request.POST
    nome = data.get('nome')
    sobrenome = data.get('sobrenome')
    mensagem = data.get('mensagem')
    email = data.get('email')
    objeto = Contato(nome=nome, sobrenome=sobrenome, email=email, mensagem=mensagem)
    try:
        objeto.save()
    except:
        return redirect('index')
    return redirect('index')

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
{% load staticfiles %}
{% block head %}
    {% include 'head.html' %}
    <link rel="stylesheet"
          href="//cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
{% endblock %}

<body>

<div id="all">

    {% include 'menu.html' %}

    <!-- *** LOGIN MODAL ***
_________________________________________________________ -->

    {% if success %}
        <script>
            $(document).ready(function () {
                swal("Sucesso!", '{{ success }}', "success");
            });
        </script>
    {% endif %}

    {% if error %}
        <script>
            $(document).ready(function () {
                swal("Erro!", '{{ error }}', "error");
            });
        </script>
    {% endif %}

    <div class="modal fade" id="contatomodal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
        <div class="modal-dialog">

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="Login">Contato</h4>
                </div>
                <div class="modal-body">
                    <form action="/submit" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" class="form-control" name="nome" id="nome" placeholder="Seu Nome"
                                   required>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="sobrenome" id="sobrenome"
                                   placeholder="Sobrenome" required>
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" name="email" id="email_modal"
                                   placeholder="Seu Email">
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="mensagem" id="mensagem" required></textarea>
                        </div>

                        <p class="text-center">
                            <button class="btn btn-template-main"><i class="fa fa-send"></i> Enviar</button>
                        </p>

                    </form>
                </div>
            </div>
        </div>
    </div>

    {% block content %}
    {% endblock %}

    <!-- /.bar -->

    <div id="get-it">
        <div class="container">
            <div class="col-md-8 col-sm-12">
                <h3>Deseja criar um site para sua empresa ?</h3>
            </div>
            <div class="col-md-4 col-sm-12">
                <a href="#" data-toggle="modal" data-target="#contatomodal"
                   class="btn btn-template-transparent-primary">Contate-me</a>
            </div>
        </div>
    </div>


    <!-- *** GET IT END *** -->


    <!-- *** COPYRIGHT ***
_________________________________________________________ -->

    <div id="copyright">
        <div class="container">
            <div class="col-md-12">
                <p class="text-center">&copy; <label id="data"></label> - Caio Marinho.</p>
                <script>
                    $(function () {
                        $('#data').text(new Date().getFullYear());
                    });
                </script>
            </div>
        </div>
    </div>
    <!-- /#copyright -->

    <!-- *** COPYRIGHT END *** -->


</div>
<!-- /#all -->

<!-- #### JAVASCRIPT FILES ### -->

<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

<script src="{% static 'js/jquery.cookie.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/jquery.parallax-1.1.3.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>
<!-- owl carousel -->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>

<div id="WAButton"></div>

<link rel="stylesheet"
      href="//rawcdn.githack.com/rafaelbotazini/floating-whatsapp/3d18b26d5c7d430a1ab0b664f8ca6b69014aed68/floating-wpp.min.css">
<!--Floating WhatsApp javascript-->
<script type="text/javascript"
        src="//rawcdn.githack.com/rafaelbotazini/floating-whatsapp/3d18b26d5c7d430a1ab0b664f8ca6b69014aed68/floating-wpp.min.js"></script>

<script>
    $(function () {
        $('#WAButton').floatingWhatsApp({
            phone: '+5583991773034', //WhatsApp Business phone number International format-
            //Get it with Toky at https://toky.co/en/features/whatsapp.
            headerTitle: 'Fale comigo pelo Whastapp!', //Popup Title
            popupMessage: 'Olá, sou o Caio. Seja bem-vindo(a) por aqui, em que posso te ajudar?', //Popup Message
            showPopup: true, //Enables popup display
            buttonImage: '<img src="//rawcdn.githack.com/rafaelbotazini/floating-whatsapp/3d18b26d5c7d430a1ab0b664f8ca6b69014aed68/whatsapp.svg" />', //Button Image
            //headerColor: 'crimson', //Custom header color
            //backgroundColor: 'crimson', //Custom background button color
            position: "right"
        });
    });
</script>

</body>

</html>

app/templates/head.html
{% load staticfiles %}
<head>
    <meta charset="utf-8">
    <title>Caio Marinho - Seu negocio na internet</title>
    <meta name="description" content="Freelancer bom e barato, construindo com qualidade tudo aquilo que você planeja,
     tornando público na internet os seus serviços, e criando meios de conquistar novos clientes para você ou sua empresa.">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="keywords"
          content="freelancer, criador de site, sites online, lojas online campina grande, campina grande desenvolvedor,
          desenvolvedor, desenvolvedor multiplataforma, desenvolvedor de sites, desenvolvedor em campina grande,
          campina grande sites">

    <link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,500,700,800'
          rel='stylesheet' type='text/css'>

    <!-- Bootstrap and Font Awesome css -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- Css animations  -->
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">

    <!-- Theme stylesheet, if possible do not edit this stylesheet -->
    <link href="{% static 'css/style.default.css' %}" rel="stylesheet" id="theme-stylesheet">

    <!-- Custom stylesheet - for your changes -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!-- Responsivity for older IE -->
    <!--[if lt IE 9]>
        <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

    <!-- Favicon and apple touch icons-->
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon"/>
    <!-- owl carousel css -->

    <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script>
        window.jQuery || document.write('<script src="/static/js/jquery-1.11.0.min.js"><\/script>')
    </script>
</head>

app/templates/menu.html
{% load staticfiles %}
<header>

    <!-- *** TOP ***
_________________________________________________________ -->
    <div id="top">
        <div class="container">
            <div class="row">
                <div class="col-xs-5 contact">
                    <p class="hidden-sm hidden-xs">Contate-me 083 9 9177-3034 ou caiomarinho8@gmail.com .</p>

                    <p class="hidden-md hidden-lg"><a href="//wa.me/+5583991773034" target="_blank" data-animate-hover="pulse"><i
                            class="fa fa-phone"></i></a> <a href="//wa.me/+5583991773034" target="_blank" data-animate-hover="pulse"><i
                            class="fa fa-envelope"></i></a>
                    </p>
                </div>
                <div class="col-xs-7">
                    <div class="social">
                        <a href="//www.facebook.com/caio.fabiomarinho" target="_blank" class="external facebook" data-animate-hover="pulse"><i
                                class="fa fa-facebook"></i></a>
                        <a href="//wa.me/+5583991773034" target="_blank" class="external gplus" data-animate-hover="pulse"><i
                                class="fa fa-paper-plane"></i></a>
                        <a href="//www.linkedin.com/in/caiomarinho/" target="_blank" class="external linkedin" data-animate-hover="pulse"><i
                                class="fa fa-linkedin"></i></a>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <!-- *** TOP END *** -->

    <!-- *** NAVBAR ***
_________________________________________________________ -->

    <div class="navbar-affixed-top" data-spy="affix" data-offset-top="200">

        <div class="navbar navbar-default yamm" role="navigation" id="navbar">

            <div class="container">
                <div class="navbar-header">

                    <a class="navbar-brand home" href="/">
                        <img src="{% static 'img/caio.png' %}" alt="Universal logo" class="hidden-xs hidden-sm">
                        <img src="{% static 'img/caio.png' %}" alt="Universal logo" class="visible-xs visible-sm"><span
                            class="sr-only">Caio Marinho</span>
                    </a>

                    <div class="navbar-buttons">
                        <button type="button" class="navbar-toggle btn-template-main" data-toggle="collapse"
                                data-target="#navigation">
                            <span class="sr-only">Toggle navigation</span>
                            <i class="fa fa-align-justify"></i>
                        </button>
                    </div>
                </div>
                <!--/.navbar-header -->

                <div class="navbar-collapse collapse" id="navigation">

                    <ul class="nav navbar-nav navbar-right">
                        <li id="inicio" class="">
                            <a href="/">Inicio </a>
                        </li>
                        <li id="projetos" class="">
                            <a href="/projetos">Projetos</a>
                        </li>
                        <li id="contact" class="">
                            <a href="#" data-toggle="modal" data-target="#contatomodal">Contato</a>
                        </li>
                    </ul>

                </div>
                <!--/.nav-collapse -->

            </div>

        </div>
        <!-- /#navbar -->

    </div>

    <!-- *** NAVBAR END *** -->

</header>

app/templates/projetos.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div id="heading-breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <h1>Projetos Feitos</h1>
                </div>
                <div class="col-md-5">
                    <ul class="breadcrumb">
                        <li><a href="{% url 'index' %}">Inicio</a>
                        </li>
                        <li>Catálogo</li>
                    </ul>

                </div>
            </div>
        </div>
    </div>

    <div id="content">
        <div class="container">

            <section>

                <div class="row">
                    <div class="col-md-12">
                        <div class="heading">
                            <h2>Portfolio</h2>
                        </div>

                    </div>
                </div>

                <div class="row portfolio">
                    {% for p in projetos %}

                        <div class="col-sm-6 col-md-3">
                            <div class="box-image">
                                <div class="image">
                                    {% for foto in p.foto_set.all %}
                                            {% if foto.principal %}
                                                <img src="{{foto.foto }}"
                                                     alt="{{ p.titulo }}"
                                                     class="img-responsive"
                                                     style="height: 300px;">
                                            {% endif %}
                                        {% endfor %}
                                </div>
                                <div class="bg"></div>
                                <div class="name">
                                    <h3><a href="/projeto/{{ p.id }}">{{ p.titulo }}</a></h3>
                                </div>
                                <div class="text">
                                    <p class="hidden-sm">{{ p.desc|truncatechars:60 }}</p>

                                    <p class="buttons">
                                        <a href="/projeto/{{ p.id }}"
                                           class="btn btn-template-transparent-primary">Ver</a>
                                    </p>
                                </div>
                            </div>
                            <!-- /.box-image -->

                        </div>
                    {% endfor %}
                </div>

            </section>

        </div>
        <!-- /.container -->

    </div>

    <script>
        $(document).ready(function () {
            $('#projetos').addClass('active');
        });
    </script>
{% endblock %}

app/templates/ver_projeto.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div id="heading-breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <h1>{{ projeto.titulo }}</h1>
                </div>
                <div class="col-md-5">
                    <ul class="breadcrumb">
                        <li><a href="/">Inicio</a>
                        </li>
                        <li><a href="/projetos">Projetos</a>
                        </li>
                        <li>{{ projeto.titulo }}</li>
                    </ul>

                </div>
            </div>
        </div>
    </div>

    <div id="content">
        <div class="container">

            <section class="no-mb">
                <div class="row">
                    <div class="col-md-12">

                        <p class="lead">{{ projeto.desc }}</p>
                    </div>
                </div>
            </section>

            <section>
                <div class="project owl-carousel">
                    {% for foto in projeto.foto_set.all %}
                        <div class="item">
                            <img src="{{ foto.foto }}" alt="" class="img-responsive" style='max-height:550px;'>
                        </div>
                    {% endfor %}
                </div>
                <!-- /.project owl-slider -->
            </section>

            <section>
                <div class="row portfolio-project">
                    <div class="col-md-8">
                        <div class="heading">
                            <h3>Descricao</h3>
                        </div>
                        {{ projeto.texto|safe }}

                    </div>
                    <div class="col-md-4 project-more">
                        <div class="heading">
                            <h3>Info</h3>
                        </div>


                        <h4>Categoria</h4>
                        <p>{{ projeto.categoria.tag }}</p>


                        <h4>Criado Em</h4>
                        <p>{{ projeto.criado_em }}</p>

                    </div>
                </div>
            </section>
        </div>
        <!-- /.container -->


    </div>
{% endblock %}